Repository terraform-providers/terraform-provider-rabbitmq, pull requests merged in 2020-07, with the labels that each got.

#55 Add federation_upstream resource
  GNUmakefile
  rabbitmq/import_federation_upstream_test.go
  rabbitmq/provider.go
  rabbitmq/resource_federation_upstream.go
  rabbitmq/resource_federation_upstream_test.go
  rabbitmq/util.go
  rabbitmq/util_test.go
  scripts/docker-compose.yml
  scripts/enabled_plugins
  website/docs/r/federation-upstream.html.markdown
  website/rabbitmq.erb
Labels: dependencies, documentation, size/XL

#59 Implementation of arguments_json in Bindings
  rabbitmq/resource_binding.go
  rabbitmq/resource_binding_test.go
Labels: size/M

#48 Feature/add shovel resource
  rabbitmq/provider.go
  rabbitmq/resource_shovel.go
  rabbitmq/resource_shovel_test.go
  scripts/enabled_plugins
  website/docs/r/shovel.html.markdown
  website/rabbitmq.erb
Labels: documentation, size/XL
