Repository terraform-providers/terraform-provider-rabbitmq, pull requests merged in 2020-02, with the labels that each got.

#50 Update env variable in index.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/XS

#39 Read proxy configuration from environment
  rabbitmq/provider.go
Labels: size/XS

#52 rabbitmq_permissions: Fix error on empty permissions.
  examples/test_issues_pr/42/test.tf
  rabbitmq/resource_permissions.go
  rabbitmq/resource_permissions_test.go
Labels: size/S

#53 rabbitmq_queue: Set ForceNew on all attributes
  rabbitmq/resource_queue.go
  rabbitmq/resource_queue_test.go
Labels: size/S
