Repository terraform-providers/terraform-provider-rabbitmq, pull requests merged in 2020-01, with the labels that each got.

#47 Travis: Execute acceptance tests on dockerized RMQ.
  .travis.yml
  scripts/docker-compose.yml
  scripts/wait-rabbitmq-docker.sh
Labels: size/S

#45 Correctly handle "not found" errors
  rabbitmq/resource_vhost_test.go
  rabbitmq/util.go
Labels: size/S

#49 Topic permissions support
  go.mod
  go.sum
  rabbitmq/import_topic_permissions_test.go
  rabbitmq/provider.go
  rabbitmq/resource_permissions.go
  rabbitmq/resource_topic_permissions.go
  rabbitmq/resource_topic_permissions_test.go
  vendor/github.com/michaelklishin/rabbit-hole/.gitignore
  vendor/github.com/michaelklishin/rabbit-hole/.travis.yml
  vendor/github.com/michaelklishin/rabbit-hole/ChangeLog.md
  vendor/github.com/michaelklishin/rabbit-hole/Makefile
  vendor/github.com/michaelklishin/rabbit-hole/README.md
  vendor/github.com/michaelklishin/rabbit-hole/bindings.go
  vendor/github.com/michaelklishin/rabbit-hole/channels.go
  vendor/github.com/michaelklishin/rabbit-hole/client.go
  vendor/github.com/michaelklishin/rabbit-hole/cluster.go
  vendor/github.com/michaelklishin/rabbit-hole/common.go
  vendor/github.com/michaelklishin/rabbit-hole/connections.go
  vendor/github.com/michaelklishin/rabbit-hole/consumers.go
  vendor/github.com/michaelklishin/rabbit-hole/doc.go
  vendor/github.com/michaelklishin/rabbit-hole/error.go
  vendor/github.com/michaelklishin/rabbit-hole/exchanges.go
  vendor/github.com/michaelklishin/rabbit-hole/federation.go
  vendor/github.com/michaelklishin/rabbit-hole/go.mod
  vendor/github.com/michaelklishin/rabbit-hole/go.sum
  vendor/github.com/michaelklishin/rabbit-hole/nodes.go
  vendor/github.com/michaelklishin/rabbit-hole/permissions.go
  vendor/github.com/michaelklishin/rabbit-hole/plugins.go
  vendor/github.com/michaelklishin/rabbit-hole/policies.go
  vendor/github.com/michaelklishin/rabbit-hole/queues.go
  vendor/github.com/michaelklishin/rabbit-hole/shovels.go
  vendor/github.com/michaelklishin/rabbit-hole/topic_permissions.go
  vendor/github.com/michaelklishin/rabbit-hole/users.go
  vendor/github.com/michaelklishin/rabbit-hole/vhosts.go
  vendor/modules.txt
  website/docs/r/topic-permissions.html.markdown
  website/rabbitmq.erb
Labels: dependencies, documentation, size/XXL

#38 Update argument schema to recreate the queue
  rabbitmq/resource_queue.go
Labels: size/XS
